name: euler-project-actions
on: [push]


jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build first
        run: cd src && ghci FirstSolution.hs

      - name: Build second 
        run: cd src && ghci SecondSolution.hs

      - name: Build third
        run: cd src && ghci ThirdSolution.hs

      - name: Build fourth
        run: cd src && ghci FourthSolution.hs 

      - name: Build fifth
        run: cd src && ghci FifthSolution.hs

  lint-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.1.6'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: src/
        fail-on: warning

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test 4 task
        run: stack test