name: euler-project-actions
on: [push]


jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build first
        run: cd src && ghci FirstSolutions.hs

      - name: Build second 
        run: cd src && ghci SecondSolutions.hs

      - name: Build third
        run: cd src && ghci ThirdSolutions.hs

      - name: Build fourth
        run: cd src && ghci FourthSolutions.hs

      - name: Build fifth
        run: cd src && ghci FifthSolutions.hs

  lint-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.1.6'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: src/