name: euler-project-actions
on: [push]


jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build first
        run: ghci FirstSolutions.hs
        with:
          path: src/
      - name: Build second 
        run: ghci SecondSolutions.hs
        with:
          path: src/
      - name: Build third
        run: ghci ThirdSolutions.hs
        with:
          path: src/
      - name: Build fourth
        run: ghci FourthSolutions.hs
        with:
          path: src/
      - name: Build fifth
        run: ghci FifthSolutions.hs
        with:
          path: src/

  lint-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.1.6'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: src/