name: euler-project-actions
on: [push]


jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    with:
      path: src/
    steps:
      - uses: actions/checkout@v2
      - name: Build first
        run: ghci FirstSolutions.hs
      - name: Build second
        run: ghci SecondSolutions.hs
      - name: Build third
        run: ghci ThirdSolutions.hs
      - name: Build fourth
        run: ghci FourthSolutions.hs
      - name: Build fifth
        run: ghci FifthSolutions.hs

  lint-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.1.6'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: src/